"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Also the HMAC key of the QR start tokens: keep it stable across restarts.
SECRET_KEY = os.environ.get(
    'BASHDASH_SECRET_KEY',
    'django-insecure-)0jim@t4fa=wd2^4k1%*1s^1=g^okunei$5+^&_&3#4w!m0$=c',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('BASHDASH_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [h for h in os.environ.get('BASHDASH_ALLOWED_HOSTS', '').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'challenges',
    'game',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get('BASHDASH_DB_DIR', BASE_DIR)) / 'db.sqlite3',
        # Concurrent game writers: WAL + IMMEDIATE + busy timeout. ATOMIC_REQUESTS stays
        # False — never hold a transaction open across a sandbox run.
        # WAL note: back up with `sqlite3 db.sqlite3 ".backup …"`, not cp.
        'OPTIONS': {
            'transaction_mode': 'IMMEDIATE',
            'timeout': 20,
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Sandbox / challenges (F-01)

SANDBOX_IMAGE = os.environ.get('BASHDASH_SANDBOX_IMAGE', 'bash-dash-sandbox:latest')
CHALLENGES_YAML = BASE_DIR / 'sandbox/internal/challenge/challenges.yaml'
CHALLENGES_EXCLUDED = BASE_DIR / 'challenges/excluded.yaml'

# Game sandbox concurrency (S-01). Per process: total = worker processes × cap.
SANDBOX_MAX_CONCURRENT = int(os.environ.get('BASHDASH_SANDBOX_CONCURRENCY', 8))
SANDBOX_QUEUE_TIMEOUT_S = 10

# Game time limit (S-02)
GAME_DURATION_S = int(os.environ.get('BASHDASH_GAME_DURATION_S', 300))

# Hall of fame screen (S-05)
HALL_TOP_N = max(1, int(os.environ.get('BASHDASH_HALL_TOP_N', 10)))
HALL_RECENT_N = max(1, int(os.environ.get('BASHDASH_HALL_RECENT_N', 5)))
HALL_REFRESH_S = max(1, int(os.environ.get('BASHDASH_HALL_REFRESH_S', 5)))

# QR start gate (S-06)
# START_TOKEN_TTL_S only seeds the staff-editable GateSettings row (0 = tokens never expire).
START_TOKEN_TTL_S = max(0, int(os.environ.get('BASHDASH_START_TOKEN_TTL_S', 900)))
# Keep this at most half the smallest TTL staff will use, so a freshly shown QR has life left.
START_TOKEN_ROTATE_S = max(10, int(os.environ.get('BASHDASH_START_TOKEN_ROTATE_S', 60)))
PUBLIC_BASE_URL = os.environ.get('BASHDASH_PUBLIC_URL', '').rstrip('/')
