# Generated by Django 6.1.1 on 2026-09-29 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('current_slug', models.CharField(max_length=64, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('solved', models.PositiveIntegerField(default=0)),
                ('last_solved_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('command', models.TextField()),
                ('correct', models.BooleanField()),
                ('output', models.TextField()),
                ('error', models.CharField(blank=True, max_length=255)),
                ('timed_out', models.BooleanField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_set', to='game.gamesession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['game', 'created_at'], name='game_attemp_game_id_67f233_idx')],
            },
        ),
    ]
