# Generated by Django 6.1.1 on 2026-09-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='prize_given_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
