# Generated by Django 6.1.1 on 2026-09-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamesession_prize_given_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='hidden_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
