# Generated by Django 6.1.1 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gatesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer_bonus_s', models.PositiveIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
